name: dart_assincronismo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.6.0
  # Para introduzir uma prática real de geração de identificadores únicos usando o pacote uuid.
  uuid: ^4.3.3 # Use a versão estável mais recente

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
